# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\boyif\Desktop\paddle\fitness_helper\ui\untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_fitness_helper(object):
    def setupUi(self, fitness_helper):
        fitness_helper.setObjectName("fitness_helper")
        fitness_helper.resize(649, 522)
        self.buttonBox = QtWidgets.QDialogButtonBox(fitness_helper)
        self.buttonBox.setGeometry(QtCore.QRect(230, 460, 201, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.toolButton = QtWidgets.QToolButton(fitness_helper)
        self.toolButton.setGeometry(QtCore.QRect(410, 90, 61, 31))
        self.toolButton.setObjectName("toolButton")
        self.progressBar = QtWidgets.QProgressBar(fitness_helper)
        self.progressBar.setGeometry(QtCore.QRect(140, 150, 371, 23))
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName("progressBar")
        self.textBrowser = QtWidgets.QTextBrowser(fitness_helper)
        self.textBrowser.setGeometry(QtCore.QRect(130, 200, 381, 231))
        self.textBrowser.setObjectName("textBrowser")
        self.label = QtWidgets.QLabel(fitness_helper)
        self.label.setGeometry(QtCore.QRect(0, 20, 641, 41))
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.file_path_input = QtWidgets.QLineEdit(fitness_helper)
        self.file_path_input.setGeometry(QtCore.QRect(140, 90, 261, 31))
        self.file_path_input.setObjectName("file_path_input")

        self.retranslateUi(fitness_helper)
        self.toolButton.clicked.connect(fitness_helper.browser)
        self.buttonBox.accepted.connect(fitness_helper.accept)
        self.buttonBox.rejected.connect(fitness_helper.reject)
        QtCore.QMetaObject.connectSlotsByName(fitness_helper)

    def retranslateUi(self, fitness_helper):
        _translate = QtCore.QCoreApplication.translate
        fitness_helper.setWindowTitle(_translate("fitness_helper", "Dialog"))
        self.toolButton.setText(_translate("fitness_helper", "..."))
        self.label.setText(_translate("fitness_helper", "肥宅运动助手"))
